In [45]:
class simple_class:
    a = 12
    @staticmethod
    def f():
        print('hello f!')

In [46]:
class_1 = simple_class()

In [47]:
class_1.a

12

In [48]:
simple_class.a

12

In [49]:
class_1.f()

hello f!


In [50]:
simple_class.f()

hello f!


In [51]:
a,b = 1,[2]

In [52]:
def test(a,b):
    a=10
    print(a)
    b.append(1)
    print(b)

In [53]:
test(a,b)

10
[2, 1]


In [54]:
print(a)

1


In [55]:
print(b)

[2, 1]


In [56]:
from access import *

In [57]:
_private_fun()

private...


In [58]:
public_var

1

In [59]:
import numpy as np

In [60]:
np.byte().itemsize*8

8

In [61]:
from sys import getsizeof
x = 2

In [62]:
getsizeof(x)

28

In [63]:
x = float(x)

In [64]:
getsizeof(x)

24

In [65]:
x

2.0

In [66]:
x = np.float128(x)

In [67]:
getsizeof(x)

48

In [68]:
x

2.0

In [72]:
y = [1,2,3]

In [73]:
y = np.int32(y)

In [74]:
y

array([1, 2, 3], dtype=int32)

In [78]:
c = np.arange(5, dtype=np.float16)

In [79]:
getsizeof(c)

106

In [80]:
c

array([ 0.,  1.,  2.,  3.,  4.], dtype=float16)

In [81]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int16)

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [83]:
a.size

9

In [84]:
a.shape

(3, 3)

In [85]:
b = a[0,:]

In [86]:
b

array([1, 2, 3], dtype=int16)

In [87]:
a[2,2]

9

In [88]:
b[1]

2

In [89]:
a[2,2] = 10

In [90]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]], dtype=int16)

In [91]:
b.shape

(3,)