In [15]:
import numpy as np

In [16]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int16)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [18]:
a.size

9

In [35]:
x,y = a.shape

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int16')

In [22]:
b = a[0,:]

In [23]:
b

array([1, 2, 3], dtype=int16)

In [24]:
b.shape

(3,)

In [39]:
c = a[0:int(x - 2),0:int(y-2)]

In [40]:
c

array([[1]], dtype=int16)

In [45]:
z = np.zeros(shape=(4,5))

In [46]:
z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [53]:
e = np.empty(shape=(2,2))

In [54]:
e

array([[ 0.,  0.],
       [ 0.,  0.]])

In [55]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int16)

In [56]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [57]:
a.flat[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [58]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [59]:
a.itemsize

2

In [60]:
g = np.arange(12,24).reshape(3,4)

In [61]:
g

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
g.flatten()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [64]:
g.flat[6]

18

In [66]:
a.base is None

True

In [67]:
b.base

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [69]:
np.random.random(5)

array([ 0.66626832,  0.08805164,  0.50621374,  0.01738747,  0.11474824])

In [70]:
np.random.rand(3,2)

array([[ 0.80780326,  0.21592371],
       [ 0.10275121,  0.2562192 ],
       [ 0.13161652,  0.66829655]])

In [72]:
np.random.randn(2,4)

array([[ 0.45945954, -0.86859302, -1.89888549,  0.14282298],
       [-0.54273995, -0.21642933, -2.08162378,  0.4742297 ]])

In [75]:
f = np.arange(1,5)

In [76]:
f

array([1, 2, 3, 4])

In [77]:
f = np.diag(f)

In [78]:
f

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [81]:
?np.ndarray.tofile()