In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
arr = np.arange(0,11,2)

In [6]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [9]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [10]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [11]:
np.random.rand(5)

array([ 0.3707341 ,  0.71000766,  0.77776922,  0.81974198,  0.12258792])

In [12]:
np.random.rand(5,5)

array([[ 0.14332759,  0.9158862 ,  0.75463679,  0.90169633,  0.02033666],
       [ 0.93654956,  0.33491879,  0.63425343,  0.69379287,  0.73477411],
       [ 0.78920933,  0.66877585,  0.73599207,  0.56003015,  0.72325371],
       [ 0.25608237,  0.61018677,  0.23526288,  0.10381062,  0.59393865],
       [ 0.2072231 ,  0.67342091,  0.34789501,  0.50340263,  0.2318661 ]])

In [13]:
np.random.randn(2)

array([-2.28385526,  0.29416409])

In [14]:
np.random.randint(1,100, 3)

array([15, 33, 34])

In [15]:
arr = np.arange(25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
ranarr

array([ 7, 17, 14, 17, 48, 22, 14,  4, 17, 25])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr.max()

48

In [21]:
ranarr.min()

4

In [22]:
ranarr.argmax()

4

In [23]:
ranarr.argmin()

7

In [24]:
arr.shape

(25,)

In [25]:
arr = arr.reshape(5,5)

In [26]:
arr.shape

(5, 5)

In [27]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
new_arr = np.arange(0,11)

In [29]:
new_arr[3]

3

In [30]:
new_arr[1:4]

array([1, 2, 3])

In [31]:
new_arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
new_arr[0:5] = 100

In [33]:
new_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][0]

5

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr = np.arange(0,11)

In [39]:
bool_arr = arr > 5

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr = np.arange(0,11)

In [43]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [47]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [48]:
arr / arr

/Users/rezahaghighi/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [49]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [50]:
np.max(arr)

10