In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [7]:
arr = np.arange(0,11,2)

In [8]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [11]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [12]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
np.random.rand(5)

array([ 0.52868748,  0.86020384,  0.61088056,  0.9098639 ,  0.45664708])

In [14]:
np.random.rand(5,5)

array([[ 0.37882294,  0.12788322,  0.95846963,  0.74014355,  0.26358254],
       [ 0.42917673,  0.79248757,  0.51229786,  0.50561758,  0.94164795],
       [ 0.45337751,  0.47766276,  0.9627676 ,  0.00427147,  0.67324197],
       [ 0.8681316 ,  0.5724777 ,  0.46370888,  0.47009635,  0.29106284],
       [ 0.81251857,  0.19812681,  0.61174209,  0.62329441,  0.40906506]])

In [15]:
np.random.randn(2)

array([-0.27433808, -0.57653775])

In [18]:
np.random.randint(1,100, 3)

array([34, 22, 73])

In [19]:
arr = np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([37, 44, 20, 15, 42, 44, 20, 22, 17, 32])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

44

In [25]:
ranarr.min()

15

In [26]:
ranarr.argmax()

1

In [27]:
ranarr.argmin()

3

In [28]:
arr.shape

(25,)

In [29]:
arr = arr.reshape(5,5)

In [30]:
arr.shape

(5, 5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
new_arr = np.arange(0,11)

In [35]:
new_arr[3]

3

In [36]:
new_arr[1:4]

array([1, 2, 3])

In [37]:
new_arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
new_arr[0:5] = 100

In [39]:
new_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])

In [45]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d[0][0]

5

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [54]:
arr = np.arange(0,11)

In [57]:
bool_arr = arr > 5

In [58]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [60]:
arr = np.arange(0,11)

In [61]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [65]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [66]:
arr / arr

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [67]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [68]:
np.max(arr)

10